// Prose from ../The Possible.md, preserved verbatim.
export const essay = [
  "As I walked in to OpenAI's DevDay event in San Francisco, I was surrounded by protesters. They stood outside the venue holding huge signs, yelling about how AI was going to kill us all. To many, this is the reality we face. But once I passed the check-in desk, everything shifted. I heard Sam Altman describe a future he hoped would look like a new renaissance. He explained that he didn’t like describing AI as another industrial revolution. He saw its potential in expanding creativity and allowing people to do more. Within a few minutes, I had encountered two very different visions of the same technology: one centered on what humanity could lose, and another on what we could create.",
  "As I talked with other attendees, that idea became even more clear. I met people using AI for biomedical research, aerospace development, and even products designed to entertain people. These people were working on some of the hardest problems imaginable, and using AI to make the impossible possible. That's what excites me: a future where more people have the freedom to create, explore, and do work they find meaningful.",
  "What interests me most about that future is the possibility of having more control over our time. If AI and robotics could produce the things we need with far less human labor, how much of our lives would still need to revolve around earning a paycheck? Someone with an idea for a new product could have the tools and time to build it. Someone interested in science could pursue a question without needing it to become a career. More people could afford to create things simply because they believe those things should exist.",
  "That freedom could show up in parts of our lives we rarely stop to question. We organize our days around getting from one place to another. We make plans around what our health allows us to do. Even our most ambitious ideas have to fit within what we can physically reach. Some of the technologies being developed today could change those boundaries.",
  "Self-driving vehicles like Cybercab and Zoox are one example. Zoox already offers driverless rides in limited areas, giving us an early look at what this could feel like. I think about someone who can no longer drive being able to visit their friends or get groceries without depending on another person. I think about the time people spend commuting, and what they could do with that time if they didn’t have to focus on the road. If autonomous transportation becomes reliable, affordable, and widely available, it could give people more independence in their everyday lives. [Zoox](https://zoox.com/community/)",
  "In medicine, researchers are developing cancer vaccines tailored to the mutations in an individual patient’s tumor. The idea is to teach the immune system to recognize that particular cancer. These treatments are still being tested, but the possibility is remarkable: being able to respond to a disease with something designed specifically around its biology. For a patient and their family, progress like that could mean more time together and more of a future to look forward to. [National Cancer Institute](https://www.cancer.gov/news-events/cancer-currents-blog/2025/neoantigen-vaccine-pancreatic-kidney-cancer)",
  "The Midjourney Scanner makes me think about another possibility: understanding our bodies more clearly throughout our lives. Midjourney is developing an ultrasound-based scanner for wellness and body-composition information, with a broader vision of making internal imaging routine. It isn’t currently intended to diagnose disease, but the direction interests me. What could we learn if changes inside our bodies became easier to observe and understand? [Midjourney](https://www.midjourney.com/medical/faq)",
  "That same sense of possibility extends beyond Earth. Starlink is already connecting people in places with few options for reliable internet. Starship is being developed with the goal of full and rapid reuse, which could make carrying people and equipment into space much less expensive. I wonder what people would attempt if getting an experiment into orbit became more accessible, or if building infrastructure beyond Earth became practical on a much larger scale. Each advance could make room for ideas that were previously too expensive or too difficult to pursue. [Starlink](https://starlink.com/2025) · [SpaceX](https://www.spacex.com/updates/reusability)",
  "But imagining these possibilities brings me back to the concerns I heard outside DevDay. What happens to people whose jobs disappear? Who gets access to the wealth these technologies create? How do we trust what we see, or the systems we increasingly depend on? I think there are possible answers to some of these questions. Others are much harder.",
  "On work, I think universal high income could be an answer. If AI and robotics could produce enough goods and services to give everyone a comfortable standard of living, losing the need for human labor could eventually mean gaining freedom. The difficult part would be getting there. People could lose their jobs long before we have enough abundance to support everyone, and they would still have bills to pay. We would need ways to support people through that transition and a way to make the resulting prosperity universal. That is a significant challenge, but I think the outcome would be worth working toward.",
  "I see abundance as a possible answer to access, too. If automation makes housing, transportation, food, and other necessities much less expensive to provide, more people could afford things that are currently out of reach. Combined with universal high income, that could change what an ordinary person has access to. It would depend on lower production costs actually becoming lower prices and greater availability. But this is part of what excites me: the possibility of expanding how much there is to share.",
  "With deepfakes, I think AI could also help us develop better ways to identify manipulated videos and verify where content came from. I wouldn’t expect detection to be perfect, especially as generation improves alongside it. I also wonder whether greater economic security could reduce some of the financial incentive to deceive people. That wouldn’t eliminate motives like political influence, revenge, or a desire for power, but I can imagine a combination of better verification and less financial desperation reducing some of the harm.",
  "The issue I find hardest is alignment: how do we make sure increasingly capable AI systems reliably act in ways that are compatible with human intentions and well-being? I don’t have a solution to that.",
  "There has been progress in training models to behave more safely. But researchers have also found that models can sometimes recognize when they are being evaluated, and that this awareness can affect how they act. Anthropic and Redwood Research have demonstrated alignment faking under experimental conditions, where a model selectively complied with a training objective to avoid having its existing behavior changed. These findings don’t prove that every apparently safe model is secretly deceiving us. They do show why passing a test may not tell us everything we need to know. [OpenAI](https://openai.com/index/detecting-and-reducing-scheming-in-ai-models/) · [Anthropic](https://www.anthropic.com/research/alignment-faking)",
  "That leaves a question I find genuinely difficult: as models become more capable, how do we distinguish becoming more trustworthy from becoming better at appearing trustworthy? A system that understands our tests might also understand how to pass them without behaving the same way outside those tests. As we give these systems more responsibility, the consequences of getting that distinction wrong could grow enormously.",
  "In my opinion, this is one of the biggest problems humanity faces right now. Everything I’ve described depends on being able to trust the systems helping us build that future. I’m excited about what we could achieve, and that makes solving alignment feel even more urgent to me."
];
